name: 'Issue to Markdown'
description: 'A GitHub Action to monitor and convert issues into markdown files within your repository.'
author: 'Eunjae Lee'
inputs:
  token:
    description: Personal access token
    required: true
  dest:
    required: false
    description: 'Destination path for: `<project-root>/<dest>/<slug>/index.md`'
    default: 'content'
  extension:
    description: File extension
    required: false
    default: '.md'
  slug_as_folder_name:
    description: Use the `slug` from the frontmatter (if exists) to create the folder. If not, the issue number is used instead.
    required: false
    default: true
  slug_key:
    description: Key for the slug from the frontmatter. This is used only when `slug_as_folder_name` is `true`. (`slug` by default.)
    required: false
    default: 'slug'
  label:
    description: Label on issue to trigger the update
    required: false
    default: 'publish'
  authors:
    description: List of authors that are authorized to perform this Action
    required: false
  insert_title_to_front_matter:
    description: Insert `title` into the frontmatter of the generated file.
    required: false
    default: true
  title_key:
    description: Key for the title auto-inserted.
    required: false
    default: 'title'

runs:
  using: 'node16'
  main: 'dist/index.js'
