on:
  issues:
    types:
      - labeled

jobs:
  run_if_label_matches:
    if: github.event.label.name == 'publish' || github.event.label.name == 'PUBLISH'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
